### PR TITLE
When comparing timezones, explicitly use UTC.

### LINKED ISSUE #497: "TypeError: can't compare offset-naive and offset-aware datetimes" when attempting to run with oauth enabled
python version: 3.8
webviz-config version: 0.3.2

When attempting to run a webviz server with oauth enabled, the server encounters an internal error. The error message originates from checking whether the oauth token has expired:
```
  File "/.../venv/lib/python3.8/site-packages/webviz_config/_oauth2.py", line 133, in check_and_set_token_expiry
    if current_date > expiration_date:
TypeError: can't compare offset-naive and offset-aware datetimes
```

The origin of the error appears to be the storage of the expiration date as a session object. When the datetime gets stored as a session object, it gets serialized into a timezone-aware object (see https://github.com/pallets/flask/blob/0.10.1/flask/sessions.py#L73 (old version of flask, but implementation detail is the same on more recent versions) and https://werkzeug.palletsprojects.com/en/2.0.x/http/).

We can fix the symptom by making sure that we explicitly use datetime objects with a utc date.

### PR DESCRIPTION
**Pull request by mhwaage**
If not setting a timezone, the timezone will be timezone naive. However, this will get serialized to a timezone-aware
timezone when being stored as a session object. This causes later comparisons to fail, since
we end up compariong timezone aware to timezone naive objects. Instead, always explicitly create timezone-aware datetimes

### Contributor checklist

- [x] :tada: This PR closes #497 
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`, and added it if should be communicated there.

### CODE REVIEW

**Comment by mhwaage** [comment]
wrt testing, as far as I can tell there are no tests for the oauth implementation currently. Adding it would require some amount of mocking, I am not sure if that would be considered in scope?

**Review by anders-kiaer — APPROVED** [review]
LGTM, thanks @mhwaage 🚀  If @thezultimate also gives 👍 we can merge this as is.

Perhaps this is worth a changelog entry? E.g. add 
```
### Fixed
- [#498](https://github.com/equinor/webviz-config/pull/498) - Explicitly use UTC when comparing time zones in the `OAuth` implementation.
```
under the `[UNRELEASED]` section in [`./CHANGELOG.md`](https://github.com/equinor/webviz-config/blob/master/CHANGELOG.md).

**Comment by thezultimate** [comment]
Thanks @mhwaage for the PR of the fix. I managed to reproduce the issue. It worked when I used an old version of Flask (version 1.1.2), but failed when I used the latest version of Flask (version 2.0.1). I will continue testing in the morning to see if the automatic token refresh works properly with the new code. Please be patient :)

**Review by thezultimate — APPROVED** [review]

**Comment by thezultimate** [comment]
Works nicely. Approved :)

**Pull request merged**
