### PR TITLE
Specify menu width

### LINKED ISSUE #291: Menu disappears if plugin content is broad (e.g. Dash `DataTables`)
Regression bug after #279.

### LINKED ISSUE #301: Limit width of menu on the left hand side
**Is your feature request related to a problem? Please describe.**
If users write long page titles, the menu can be quite wide. Would be better to have more line breaks and leave more room for the plugin visualization.

**Describe the solution you'd like**
A max width for the menu.

**Describe alternatives you've considered**
Possibility for forced line breaks with e.g. `\n` using `white-space: pre-wrap;` in [div.styledButton.tab](https://github.com/equinor/webviz-config/blob/623ab6fbabf85dd658be1d668d9f6e216939fdd2/webviz_config/static/assets/webviz_layout.css#L11-L27)

### PR DESCRIPTION
**Pull request by HansKallekleiv**
*Insert a description of your pull request (PR) here, and check off the boxes below when they are done.*

---

### Contributor checklist

- [x] :tada: This PR closes #291 and closes #301.
- [x] :scroll: I have broken down my PR into the following tasks:
   - [x] Overflow page content 
   - [x] Tested on existing webviz subsurface plugins

### CODE REVIEW

**Comment by anders-kiaer** [comment]
Seeing #301, are we better of having min+max width specified on the menu?

It is also a bit unclear to me how we want to solve overflow-x on individual dashboards/plugins, and if that would be in conflict with the current addition in this PR. E.g. the parallell coordinates plugin is typically very vide, and the user will have to scroll all the way to the bottom to scroll it horizontally. Might want to have overflow scrollbar on the plot/plugin itself? Maybe we should try to solve both at the same time?

**Comment by HansKallekleiv** [comment]
Agreed. min/max width on sidebar is better.

**Comment by anders-kiaer** [comment]
As discussed in sprint meeting today, @HansKallekleiv will try with `width` only and some `vw%` (+ verify that breakpoint functionality still make us support narrow displays).

**Review by anders-kiaer — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
